{{- if and .Values.istio.enabled (or .Values.istio.trafficManagement.canary.enabled .Values.istio.trafficManagement.trafficShifting.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-canary
  labels:
    app: {{ .Release.Name }}
    version: {{ .Values.istio.trafficManagement.canary.version | default .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-canary
    app.kubernetes.io/version: {{ .Values.application.version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    canary: "true"
  annotations:
    {{- if .Values.monitoring.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: {{ .Values.istio.trafficManagement.canary.version | default .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
  strategy:
    {{- toYaml .Values.deployment.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Values.istio.trafficManagement.canary.version | default .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
        canary: "true"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      {{- if .Values.gke.enabled }}
      nodeSelector:
        {{- toYaml .Values.gke.nodeSelectors | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-canary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          {{- if .Values.deployment.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.deployment.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
          env:
            {{- range .Values.env.normal }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: CANARY_RELEASE
              value: "true"
            {{- range .Values.env.secrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          volumeMounts:
            {{- if .Values.container.nginx.enabled }}
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            {{- end }}
            {{- if .Values.configMaps.enabled }}
            - name: config-volume
              mountPath: /usr/share/nginx/html/assets/config
            {{- end }}
      volumes:
        {{- if .Values.container.nginx.enabled }}
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-nginx-config
        {{- end }}
        {{- if .Values.configMaps.enabled }}
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
        {{- end }}
{{- end }}