{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-dr
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  host: {{ .Values.istio.destinationRule.host | default .Release.Name }}
  {{- if .Values.istio.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- if .Values.istio.destinationRule.trafficPolicy.loadBalancer }}
    loadBalancer:
      {{- toYaml .Values.istio.destinationRule.trafficPolicy.loadBalancer | nindent 6 }}
    {{- end }}
    
    {{- if .Values.istio.destinationRule.trafficPolicy.connectionPool }}
    connectionPool:
      {{- toYaml .Values.istio.destinationRule.trafficPolicy.connectionPool | nindent 6 }}
    {{- end }}
    
    {{- if .Values.istio.trafficManagement.circuitBreaker.enabled }}
    outlierDetection:
      consecutiveErrors: {{ .Values.istio.trafficManagement.circuitBreaker.consecutiveErrors }}
      interval: {{ .Values.istio.trafficManagement.circuitBreaker.interval }}
      baseEjectionTime: {{ .Values.istio.trafficManagement.circuitBreaker.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.istio.trafficManagement.circuitBreaker.maxEjectionPercent }}
      {{- if .Values.istio.trafficManagement.circuitBreaker.outlierDetection }}
      {{- with .Values.istio.trafficManagement.circuitBreaker.outlierDetection }}
      consecutiveGatewayErrors: {{ .consecutiveGatewayErrors }}
      {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  
  # Define subsets for different versions
  subsets:
    - name: {{ .Values.istio.trafficManagement.stableVersion | default "v1" }}
      labels:
        version: {{ .Values.istio.trafficManagement.stableVersion | default "v1" }}
    {{- if or .Values.istio.trafficManagement.canary.enabled .Values.istio.trafficManagement.trafficShifting.enabled }}
    - name: {{ .Values.istio.trafficManagement.canary.version | default .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
      labels:
        version: {{ .Values.istio.trafficManagement.canary.version | default .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
    {{- end }}
{{- end }}