{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}-vs
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    {{- range .Values.istio.virtualService.gateways }}
    - {{ .Release.Name }}-{{ . }}
    {{- end }}
  http:
    {{- if .Values.istio.trafficManagement.canary.enabled }}
    # Route traffic based on header to canary version
    - match:
        - headers:
            {{ .Values.istio.trafficManagement.canary.header }}:
              exact: {{ .Values.istio.trafficManagement.canary.headerValue | default "true" }}
      route:
        - destination:
            host: {{ .Release.Name }}
            subset: {{ .Values.istio.trafficManagement.canary.version | default "v2" }}
    {{- end }}

    {{- if .Values.istio.trafficManagement.trafficShifting.enabled }}
    # Traffic splitting between versions
    - route:
        - destination:
            host: {{ .Release.Name }}
            subset: {{ .Values.istio.trafficManagement.trafficShifting.stableVersion | default "v1" }}
          weight: {{ .Values.istio.trafficManagement.trafficShifting.stableWeight | default 90 }}
        - destination:
            host: {{ .Release.Name }}
            subset: {{ .Values.istio.trafficManagement.trafficShifting.canaryVersion | default "v2" }}
          weight: {{ .Values.istio.trafficManagement.trafficShifting.canaryWeight | default 10 }}
    {{- else }}
    # Default route to stable version
    - route:
        - destination:
            host: {{ .Release.Name }}
            {{- if or .Values.istio.trafficManagement.canary.enabled .Values.istio.destinationRule.enabled }}
            subset: {{ .Values.istio.trafficManagement.stableVersion | default "v1" }}
            {{- end }}
    {{- end }}

      {{- if .Values.istio.trafficManagement.timeout }}
      timeout: {{ .Values.istio.trafficManagement.timeout }}
      {{- end }}

      {{- if .Values.istio.trafficManagement.retries.enabled }}
      retries:
        attempts: {{ .Values.istio.trafficManagement.retries.attempts }}
        perTryTimeout: {{ .Values.istio.trafficManagement.retries.perTryTimeout }}
        retryOn: {{ .Values.istio.trafficManagement.retries.retryOn }}
      {{- end }}

      {{- if .Values.istio.trafficManagement.faultInjection.enabled }}
      fault:
        {{- if .Values.istio.trafficManagement.faultInjection.delay }}
        delay:
          percentage:
            value: {{ .Values.istio.trafficManagement.faultInjection.delay.percentage }}
          fixedDelay: {{ .Values.istio.trafficManagement.faultInjection.delay.fixedDelay }}
        {{- end }}
        {{- if .Values.istio.trafficManagement.faultInjection.abort }}
        abort:
          percentage:
            value: {{ .Values.istio.trafficManagement.faultInjection.abort.percentage }}
          httpStatus: {{ .Values.istio.trafficManagement.faultInjection.abort.httpStatus }}
        {{- end }}
      {{- end }}

      {{- if .Values.istio.trafficManagement.corsPolicy }}
      corsPolicy:
        {{- toYaml .Values.istio.trafficManagement.corsPolicy | nindent 8 }}
      {{- end }}
{{- end }}