{{- if and .Values.ssl.enabled .Values.ssl.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssl.secret.name }}
  labels:
    app: {{ .Values.application.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.ssl.secret.crtFile | b64enc }}
  tls.key: {{ .Files.Get .Values.ssl.secret.keyFile | b64enc }}
{{- end }}