# Development Dockerfile for Angular application
FROM node:20-alpine

# Install dependencies
RUN apk add --no-cache chromium
ENV CHROME_BIN=/usr/bin/chromium-browser

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Set development-specific environment variables
ENV NODE_ENV=development

# Expose the development server port
EXPOSE 4200

# Start the development server
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll", "500"]