apiVersion: v2
name: angular-app
description: A Helm chart for deploying Angular applications with Nginx on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - angular
  - nginx
  - frontend
maintainers:
  - name: Your Name
    email: your.email@example.com
sources:
  - https://github.com/yourusername/angular-app
icon: https://angular.io/assets/images/logos/angular/angular.svg