# Default values for Angular application
# This is a YAML-formatted file.

application:
  name: angular-app
  version: 1.0.0

# Deployment configuration
replicaCount: 2
image:
  repository: gcr.io/your-project/angular-app
  tag: latest
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""

# Resource configuration
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration (non-Istio)
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]
  tls: []

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod configuration
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Istio configuration
istio:
  enabled: true
  gateway:
    hosts:
      - "example.com"
      - "www.example.com"
    httpsRedirect: true
    tls:
      enabled: true
      mode: SIMPLE
      credentialName: angular-tls-cert

  virtualService:
    hosts:
      - "example.com"
      - "www.example.com"
  
  # Traffic management configurations
  trafficManagement:
    # Canary deployment with header-based routing
    canary:
      enabled: true
      header: "x-canary"
      version: "v2"
    
    # Traffic shifting / weighted routing
    trafficShifting:
      enabled: true
      stableVersion: "v1"
      stableWeight: 90
      canaryVersion: "v2"
      canaryWeight: 10
    
    # Circuit breaker configuration
    circuitBreaker:
      enabled: true
      maxConnections: 100
      connectTimeout: "30ms"
      http1MaxPendingRequests: 1
      maxRequestsPerConnection: 1
      maxRetries: 3
      consecutive5xxErrors: 1
      interval: "1s"
      baseEjectionTime: "3m"
      maxEjectionPercent: 100
    
    # Fault injection for testing
    faultInjection:
      enabled: true
      header: "x-test-fault"
      headerValue: "inject-fault"
      targetVersion: "v1"
      delayPercentage: 100.0
      fixedDelay: "5s"
      abortPercentage: 10.0
      errorCode: 500
    
    # Request timeouts
    timeout: "10s"
    
    # Retry policy
    retries:
      attempts: 3
      perTryTimeout: "2s"
      retryOn: "gateway-error,connect-failure,refused-stream"

  # Security configurations
  security:
    # Authorization policies
    authorization:
      enabled: true
      action: ALLOW
      rules:
        - from:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
          to:
            methods: ["GET", "POST"]
            paths: ["/api/*", "/assets/*", "/*"]
    
    # mTLS configuration
    peerAuthentication:
      enabled: true
      mtlsMode: STRICT
      portLevelMtls:
        8080: PERMISSIVE
  
  # Telemetry configuration
  telemetry:
    enabled: true
    metricsProviders:
      - prometheus
    metricsOverrides:
      - metric: REQUEST_COUNT
        mode: CLIENT_AND_SERVER
        tagOverrides:
          app: "angular-app"
      - metric: REQUEST_DURATION
        mode: CLIENT_AND_SERVER
        tagOverrides:
          app: "angular-app"
    tracing:
      providers:
        - zipkin
      samplingRate: 100.0
    accessLogging:
      providers:
        - envoy