apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: angular-circuit-breaker
  namespace: angular-app
spec:
  host: angular-app
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
        maxRetries: 3
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100