apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: angular-fault-injection
  namespace: angular-app
spec:
  hosts:
  - "test.example.com"  # Use a separate test domain
  gateways:
  - angular-gateway
  http:
  - match:
    - headers:
        # Only inject faults when this header is present
        x-test-fault:
          exact: "inject-fault"
    route:
    - destination:
        host: angular-app
        subset: v1
        port:
          number: 80
    fault:
      delay:
        percentage:
          value: 100.0
        fixedDelay: 5s
      abort:
        percentage:
          value: 10.0
        httpStatus: 500
  - route:
    - destination:
        host: angular-app
        subset: v1
        port:
          number: 80