name: Helm Chart Lint and Test

on:
  push:
    paths:
      - 'helm-chart/**'
      - '.github/workflows/helm-lint.yml'
  pull_request:
    paths:
      - 'helm-chart/**'
      - '.github/workflows/helm-lint.yml'

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml --charts helm-chart

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: github.event_name != 'pull_request'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --charts helm-chart
        if: github.event_name != 'pull_request'